plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js
packageExtensions:
  react-scripts@*:
    dependencies:
      ts-pnp: "^1.2.0"
