name: Deploy Web
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Setup environment"
        run: "yarn set version berry"
      - run: "yarn plugin import workspace-tools"
      - run: "yarn add shx"
      - run: "yarn run copy_patch"
      - name: Install Packages
        run: yarn install
      - name: Build page
        run: yarn workspace web build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
